---
# tasks file for bench_time.runtime

# The following includes are necessary, because loops don't work with blocks
# So the tasks are nested in subtasks to create nested loops
#
# Nested Loops
# Ressource Limit     - use bench_time__resource_limits and set bench_loop_target_reccource_limit
# Runtime             - use bench_time__runtimes and set bench_loop_target_runtime
# Container           - use bench_time__target_images + bench_time__not_nabla_images and set bench_loop_target_image_name  <- this file
# Number of instances - no varables set or used   
# repeat              - repeats the bechmark as long as bench_time__repeat and set bench_loop_repeat_number
# benchmark           - do the real benchmark 

- name: Loop - different target image types
  include_tasks: instance_number.yml
  loop: "{{ bench_time__target_images }}"
  loop_control:
    loop_var: bench_loop_target_image_name

- name: Loop - different target image types
  include_tasks: instance_number.yml
  loop: "{{ bench_time__not_nabla_images }}"
  loop_control:
    loop_var: bench_loop_target_image_name
  when: bench_loop_target_runtime != 'runnc'

- name: Reboot the machine
  reboot:
    reboot_timeout: 3600