---
# tasks file for bench_iperf.runtime

# The following includes are necessary, because loops don't work with blocks
# So the tasks are nested in subtasks to create nested loops
#
# Nested Loops
# Ressource Limit     - use bench_iperf__resource_limits and set bench_loop_target_reccource_limit
# Runtime             - use bench_iperf__runtimes and set bench_loop_target_runtime
# Container           - use bench_iperf__target_images + bench_iperf__not_nabla_images and set bench_loop_target_image_name  <- this file
# Number of instances - no varables set or used   
# repeat              - repeats the bechmark as long as bench_iperf__repeat and set bench_loop_repeat_number
# benchmark           - do the real benchmark 

- name: Loop - different target image types
  include_tasks: instance_number.yml

- name: Reboot the machine
  reboot:
    reboot_timeout: 3600